---
name: Web App - TST

on:
  pull_request:

permissions: read-all
concurrency: RunOnlyOnceDeployTst #can be any string, the second job will be queued after the first one is finished

env:
  AZURE_WEBAPP_NAME: app-wdd-tst
  AZURE_WEBAPP_SLOT_NAME: tst
  AZURE_WEBAPP_SLOT_API_NAME: tst-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish --configuration Release --no-build --output ./published/api MyWebApp.Api/MyWebApp.Api.csproj
  
      - name: Publish Client
        run: dotnet publish --configuration Release --no-build --output ./published/client MyWebApp.Client/MyWebApp.Client.csproj
  
      - name: 'Deploy API to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_API_NAME }}
          publish-profile: ${{ secrets.API-TST-PUBLISHPROFILE }}
          package: './published/api'
  
      - name: 'Deploy Client to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }} 
          package: './published/client'

