---
name: Web App - TST

on:
  pull_request:

permissions: read-all
concurrency: RunOnlyOnceDeployTst #can be any string, the second job will be queued after the first one is finished

env:
  AZURE_WEBAPP_NAME: app-wdd-tst
  AZURE_WEBAPP_SLOT_NAME: tst
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./published
  
      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.azureWebAppPublishProfile }} 
          package: './published'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.TST_PUBLISH_PROFILE }}
          package: './published'
